import type { RepoFacts } from "./scanner"
import { SITE_URL } from "./site-url"

// 根据扫描到的事实，用模板生成基础 AGENTS.md
// 不依赖 LLM，保证即使没有 API Key 也能输出结果
export function generateAgentsMdTemplate(facts: RepoFacts): string {
  const lines: string[] = []

  // Header
  lines.push(`# ${facts.repo}`)
  lines.push("")
  if (facts.description) {
    lines.push(`> ${facts.description}`)
    lines.push("")
  }

  // Tech Stack
  lines.push("## Tech Stack")
  lines.push("")
  const stackItems: string[] = []
  if (facts.language) stackItems.push(`- **Language:** ${facts.language}`)
  if (facts.framework) stackItems.push(`- **Framework:** ${facts.framework}`)
  if (facts.packageManager) stackItems.push(`- **Package Manager:** ${facts.packageManager}`)
  if (facts.buildTool) stackItems.push(`- **Build Tool:** ${facts.buildTool}`)
  if (facts.testFramework) stackItems.push(`- **Test Framework:** ${facts.testFramework}`)
  if (stackItems.length === 0) {
    stackItems.push("- Standard project structure")
  }
  lines.push(...stackItems)
  lines.push("")

  // Setup
  const hasSetup = facts.devCommand || facts.buildCommand
  if (hasSetup) {
    lines.push("## Setup")
    lines.push("")
    if (facts.packageManager === "pnpm") {
      lines.push("```bash")
      lines.push("pnpm install")
      lines.push("```")
    } else if (facts.packageManager === "yarn") {
      lines.push("```bash")
      lines.push("yarn install")
      lines.push("```")
    } else if (facts.packageManager === "bun") {
      lines.push("```bash")
      lines.push("bun install")
      lines.push("```")
    } else if (facts.packageManager === "npm") {
      lines.push("```bash")
      lines.push("npm install")
      lines.push("```")
    } else if (facts.packageManager === "poetry") {
      lines.push("```bash")
      lines.push("poetry install")
      lines.push("```")
    } else if (facts.packageManager === "pip") {
      lines.push("```bash")
      lines.push("pip install -r requirements.txt")
      lines.push("```")
    } else if (facts.language === "Go") {
      lines.push("```bash")
      lines.push("go mod download")
      lines.push("```")
    } else if (facts.language === "Rust") {
      lines.push("```bash")
      lines.push("cargo build")
      lines.push("```")
    }
    lines.push("")
  }

  // Development
  if (facts.devCommand) {
    lines.push("## Development")
    lines.push("")
    lines.push("Start the development server:")
    lines.push("")
    lines.push("```bash")
    lines.push(facts.devCommand)
    lines.push("```")
    lines.push("")
  }

  // Build
  if (facts.buildCommand) {
    lines.push("## Build")
    lines.push("")
    lines.push("```bash")
    lines.push(facts.buildCommand)
    lines.push("```")
    lines.push("")
  }

  // Testing
  if (facts.testCommand) {
    lines.push("## Testing")
    lines.push("")
    lines.push("Run the test suite:")
    lines.push("")
    lines.push("```bash")
    lines.push(facts.testCommand)
    lines.push("```")
    lines.push("")
    if (facts.testDir) {
      lines.push(`Tests are located in \`/${facts.testDir}\`.`)
      lines.push("")
    }
  }

  // Linting
  if (facts.lintCommand) {
    lines.push("## Linting")
    lines.push("")
    lines.push("```bash")
    lines.push(facts.lintCommand)
    lines.push("```")
    lines.push("")
  }

  // Project Structure
  const hasStructure = facts.srcDir || facts.testDir || facts.isMonorepo
  if (hasStructure) {
    lines.push("## Project Structure")
    lines.push("")
    if (facts.isMonorepo && facts.monorepoDirs.length > 0) {
      lines.push(
        `This is a **monorepo**. Top-level workspace directories: ${facts.monorepoDirs
          .map((d) => `\`${d}/\``)
          .join(", ")}.`,
      )
      lines.push("")
    }
    if (facts.srcDir) lines.push(`- \`${facts.srcDir}/\` — Source code`)
    if (facts.testDir) lines.push(`- \`${facts.testDir}/\` — Test files`)
    lines.push("")
  }

  // Additional Notes
  const notes: string[] = []
  if (facts.hasDocker) notes.push("- This project uses Docker for containerization.")
  if (facts.hasCi) notes.push("- CI/CD is configured via GitHub Actions.")
  if (notes.length > 0) {
    lines.push("## Notes")
    lines.push("")
    lines.push(...notes)
    lines.push("")
  }

  // Footer
  lines.push("---")
  lines.push("")
  lines.push(`*Generated by [RepoContext](${SITE_URL}) — verified against the repository codebase.*`)

  return lines.join("\n")
}

// 计算质量分数（基于扫描到的确定信息数量）
export function calculateQualityScore(facts: RepoFacts): {
  score: number
  verified: number
  total: number
  details: { label: string; verified: boolean }[]
} {
  const checks = [
    { label: "Language detected", verified: !!facts.language },
    { label: "Package manager detected", verified: !!facts.packageManager },
    { label: "Framework detected", verified: !!facts.framework },
    { label: "Test command available", verified: !!facts.testCommand },
    { label: "Build command available", verified: !!facts.buildCommand },
    { label: "Test directory found", verified: !!facts.testDir },
    { label: "Source directory found", verified: !!facts.srcDir },
  ]

  const verified = checks.filter((c) => c.verified).length
  const score = Math.round((verified / checks.length) * 100)

  return { score, verified, total: checks.length, details: checks }
}

/* ────────────────────────────────────────────────────────────────────────────
 * Multi-format export — all derive from the same RepoFacts, so they stay
 * consistent with each other and with the canonical AGENTS.md.
 * ──────────────────────────────────────────────────────────────────────────── */

/** CLAUDE.md — Anthropic Claude's repository-level context file. */
export function generateClaudeMd(facts: RepoFacts): string {
  const lines: string[] = []
  lines.push(`# ${facts.repo}`)
  lines.push("")
  if (facts.description) {
    lines.push(`> ${facts.description}`)
    lines.push("")
  }
  lines.push("This file provides repository context for Claude to work effectively in this codebase.")
  lines.push("")

  lines.push("## Tech Stack")
  lines.push("")
  if (facts.language) lines.push(`- **Language:** ${facts.language}`)
  if (facts.framework) lines.push(`- **Framework:** ${facts.framework}`)
  if (facts.packageManager) lines.push(`- **Package Manager:** ${facts.packageManager}`)
  if (facts.buildTool) lines.push(`- **Build Tool:** ${facts.buildTool}`)
  if (facts.testFramework) lines.push(`- **Test Framework:** ${facts.testFramework}`)
  lines.push("")

  const hasCmd = facts.devCommand || facts.buildCommand || facts.testCommand || facts.lintCommand
  if (hasCmd) {
    lines.push("## Commands")
    lines.push("")
    if (facts.devCommand) lines.push(`- Start dev: \`${facts.devCommand}\``)
    if (facts.buildCommand) lines.push(`- Build: \`${facts.buildCommand}\``)
    if (facts.testCommand) lines.push(`- Run tests: \`${facts.testCommand}\``)
    if (facts.lintCommand) lines.push(`- Lint: \`${facts.lintCommand}\``)
    lines.push("")
  }

  if (facts.srcDir || facts.testDir || facts.isMonorepo) {
    lines.push("## Project Layout")
    lines.push("")
    if (facts.isMonorepo && facts.monorepoDirs.length > 0) {
      lines.push(
        `This is a **monorepo**. Top-level workspace directories: ${facts.monorepoDirs
          .map((d) => `\`${d}/\``)
          .join(", ")}.`,
      )
      lines.push("")
    }
    if (facts.srcDir) lines.push(`- \`${facts.srcDir}/\` — source code`)
    if (facts.testDir) lines.push(`- \`${facts.testDir}/\` — test files`)
    lines.push("")
  }

  const notes: string[] = []
  if (facts.hasDocker) notes.push("- The project is containerized with Docker.")
  if (facts.hasCi) notes.push("- CI/CD runs on GitHub Actions.")
  if (notes.length > 0) {
    lines.push("## Notes")
    lines.push("")
    lines.push(...notes)
    lines.push("")
  }

  lines.push("---")
  lines.push("")
  lines.push(`*Generated by [RepoContext](${SITE_URL}) — verified against the repository codebase.*`)
  return lines.join("\n")
}

/** Cursor Rules — `.cursorrules` format used by Cursor IDE. */
export function generateCursorRules(facts: RepoFacts): string {
  const lines: string[] = []
  lines.push(`# Cursor Rules — ${facts.repo}`)
  lines.push("")
  if (facts.description) {
    lines.push(`Project: ${facts.description}`)
    lines.push("")
  }

  lines.push("## Tech Stack")
  const stack: string[] = []
  if (facts.language) stack.push(facts.language)
  if (facts.framework) stack.push(facts.framework)
  if (facts.buildTool) stack.push(facts.buildTool)
  if (facts.testFramework) stack.push(facts.testFramework)
  lines.push(stack.length ? stack.join(", ") : "Standard project structure")
  lines.push("")

  lines.push("## Package Manager")
  lines.push(
    facts.packageManager
      ? `Use \`${facts.packageManager}\` for dependency management (lockfile committed).`
      : `Use the repository's default package manager.`,
  )
  lines.push("")

  const hasCmd = facts.devCommand || facts.buildCommand || facts.testCommand || facts.lintCommand
  if (hasCmd) {
    lines.push("## Run")
    lines.push("")
    if (facts.devCommand) lines.push(`- Dev: \`${facts.devCommand}\``)
    if (facts.buildCommand) lines.push(`- Build: \`${facts.buildCommand}\``)
    if (facts.testCommand) lines.push(`- Test: \`${facts.testCommand}\``)
    if (facts.lintCommand) lines.push(`- Lint: \`${facts.lintCommand}\``)
    lines.push("")
  }

  if (facts.srcDir || facts.testDir) {
    lines.push("## Layout")
    lines.push("")
    if (facts.srcDir) lines.push(`- Source: \`${facts.srcDir}/\``)
    if (facts.testDir) lines.push(`- Tests: \`${facts.testDir}/\``)
    lines.push("")
  }

  const notes: string[] = []
  if (facts.hasDocker) notes.push("Project is containerized with Docker.")
  if (facts.hasCi) notes.push("CI runs on GitHub Actions.")
  if (notes.length) {
    lines.push("## Notes")
    lines.push("")
    notes.forEach((n) => lines.push(`- ${n}`))
    lines.push("")
  }

  lines.push("---")
  lines.push("")
  lines.push(`*Generated by [RepoContext](${SITE_URL}).*`)
  return lines.join("\n")
}

/** Copilot Instructions — `.github/copilot-instructions.md`. */
export function generateCopilotInstructions(facts: RepoFacts): string {
  const lines: string[] = []
  lines.push(`# Copilot Instructions — ${facts.repo}`)
  lines.push("")
  if (facts.description) {
    lines.push(facts.description)
    lines.push("")
  }

  lines.push("## Stack")
  lines.push("")
  if (facts.language) lines.push(`- Language: ${facts.language}`)
  if (facts.framework) lines.push(`- Framework: ${facts.framework}`)
  if (facts.packageManager) lines.push(`- Package manager: ${facts.packageManager}`)
  if (facts.buildTool) lines.push(`- Build tool: ${facts.buildTool}`)
  if (facts.testFramework) lines.push(`- Test framework: ${facts.testFramework}`)
  lines.push("")

  const hasCmd = facts.devCommand || facts.buildCommand || facts.testCommand || facts.lintCommand
  if (hasCmd) {
    lines.push("## Commands")
    lines.push("")
    if (facts.devCommand) lines.push(`- \`${facts.devCommand}\` — start dev server`)
    if (facts.testCommand) lines.push(`- \`${facts.testCommand}\` — run tests`)
    if (facts.lintCommand) lines.push(`- \`${facts.lintCommand}\` — run lint`)
    if (facts.buildCommand) lines.push(`- \`${facts.buildCommand}\` — build`)
    lines.push("")
  }

  const notes: string[] = []
  if (facts.srcDir) notes.push(`Source code lives in \`${facts.srcDir}/\`.`)
  if (facts.testDir) notes.push(`Tests live in \`${facts.testDir}/\`.`)
  if (facts.hasDocker) notes.push("Project is containerized with Docker.")
  if (facts.hasCi) notes.push("CI runs on GitHub Actions.")
  if (notes.length) {
    lines.push("## Notes")
    lines.push("")
    notes.forEach((n) => lines.push(`- ${n}`))
    lines.push("")
  }

  lines.push("---")
  lines.push("")
  lines.push(`*Generated by [RepoContext](${SITE_URL}).*`)
  return lines.join("\n")
}

/* ────────────────────────────────────────────────────────────────────────────
 * AGENTS.md audit — compares the existing AGENTS.md against the verified
 * facts we just scanned from the codebase and surfaces concrete fixes.
 * ──────────────────────────────────────────────────────────────────────────── */

export interface AuditIssue {
  severity: "critical" | "warning" | "info"
  category: "missing" | "outdated" | "incomplete"
  title: string
  detail: string
  fix: string
}

export interface AuditResult {
  hasIssues: boolean
  score: number
  issues: AuditIssue[]
  suggestions: string[]
  hasExisting: boolean
}

export function auditAgentsMd(facts: RepoFacts): AuditResult {
  const issues: AuditIssue[] = []
  const suggestions: string[] = []

  // No AGENTS.md at all
  if (!facts.hasAgentsMd) {
    issues.push({
      severity: "critical",
      category: "missing",
      title: "AGENTS.md is missing from the repository root",
      detail: "AI coding agents rely on AGENTS.md to understand the project before making changes.",
      fix: "Run RepoContext to generate one based on the scanned codebase facts.",
    })
    suggestions.push("Create AGENTS.md at the repository root to give AI coding agents reliable context.")
    return { hasIssues: true, score: 0, issues, suggestions, hasExisting: false }
  }

  const content = facts.agentsMdContent || ""
  const lc = content.toLowerCase()
  const has = (kw: string) => lc.includes(kw.toLowerCase())
  const hasRe = (re: RegExp) => re.test(content)

  // Framework
  if (facts.framework) {
    const head = facts.framework.split(/[\s.]/)[0]
    if (!has(facts.framework) && !hasRe(new RegExp(`\\b${head}\\b`, "i"))) {
      issues.push({
        severity: "warning",
        category: "missing",
        title: `Framework "${facts.framework}" is not mentioned`,
        detail: "AI agents need to know the framework before they can write idiomatic code.",
        fix: `Add a "Tech Stack" or "Framework" section that explicitly names ${facts.framework}.`,
      })
    }
  }

  // Package manager
  if (facts.packageManager && !has(facts.packageManager)) {
    issues.push({
      severity: "warning",
      category: "missing",
      title: `Package manager "${facts.packageManager}" is not mentioned`,
      detail: "Mentioning the package manager avoids AI agents guessing the wrong commands.",
      fix: `Document that the project uses ${facts.packageManager} (lockfile is committed).`,
    })
  }

  // Test framework
  if (facts.testFramework && !has(facts.testFramework)) {
    issues.push({
      severity: "info",
      category: "missing",
      title: `Test framework "${facts.testFramework}" is not mentioned`,
      detail: "Listing the test framework lets AI agents write tests in the right style.",
      fix: `Add a "Testing" section mentioning ${facts.testFramework}.`,
    })
  }

  // Source / test directories
  if (facts.srcDir && !has(`${facts.srcDir}/`) && !has(facts.srcDir)) {
    issues.push({
      severity: "info",
      category: "incomplete",
      title: `Source directory "${facts.srcDir}/" is not documented`,
      detail: "AI agents benefit from a clear project-layout section.",
      fix: `Add a "Project Structure" section that mentions \`${facts.srcDir}/\`.`,
    })
  }
  if (facts.testDir && !has(`${facts.testDir}/`) && !has(facts.testDir)) {
    issues.push({
      severity: "info",
      category: "incomplete",
      title: `Test directory "${facts.testDir}/" is not documented`,
      detail: "Where tests live is one of the first things AI agents need to know.",
      fix: `Add a "Testing" section that mentions \`${facts.testDir}/\`.`,
    })
  }

  // Docker
  if (facts.hasDocker && !has("docker")) {
    issues.push({
      severity: "info",
      category: "missing",
      title: "Docker usage is not mentioned",
      detail: "The repository is containerized but AGENTS.md does not mention it.",
      fix: "Add a short note about Docker so AI agents don't invent their own container workflow.",
    })
  }

  // CI
  if (facts.hasCi && !has("ci") && !has("github actions") && !has("workflow")) {
    issues.push({
      severity: "info",
      category: "missing",
      title: "CI/CD is not mentioned",
      detail: "GitHub Actions workflows exist but AGENTS.md does not mention them.",
      fix: 'Add a brief note like "CI runs on GitHub Actions".',
    })
  }

  // Length heuristic
  if (content.length < 400) {
    issues.push({
      severity: "warning",
      category: "incomplete",
      title: "AGENTS.md looks too short",
      detail: `Only ${content.length} characters — likely missing key context.`,
      fix: "Expand to cover tech stack, commands, structure, and conventions.",
    })
  }

  // Scoring
  const critical = issues.filter((i) => i.severity === "critical").length
  const warning = issues.filter((i) => i.severity === "warning").length
  const info = issues.filter((i) => i.severity === "info").length
  const score = Math.max(0, 100 - critical * 30 - warning * 15 - info * 5)

  if (issues.length === 0) {
    suggestions.push("Your AGENTS.md looks comprehensive. Re-run analysis after major project changes to keep it current.")
  } else {
    suggestions.push(
      `Address the ${issues.length} issue${issues.length > 1 ? "s" : ""} above to improve the quality of your AGENTS.md.`,
    )
    if (warning > 0) {
      suggestions.push("Add explicit mentions of your framework and package manager so AI agents don't have to guess.")
    }
  }

  return { hasIssues: issues.length > 0, score, issues, suggestions, hasExisting: true }
}

/* ────────────────────────────────────────────────────────────────────────────
 * Evidence — derives a per-claim source mapping from the verified facts so
 * the result UI can render "every statement is traceable" honestly.
 * ──────────────────────────────────────────────────────────────────────────── */

export interface EvidenceItem {
  field: string
  label: string
  value: string | null
  source: string | null
  sourceDetail?: string
  /** Fully-qualified GitHub URL pointing at the file that backs this claim. */
  sourceUrl?: string
  verified: boolean
}

/**
 * Best-effort extraction of a repository-relative path from a human-readable
 * source string. Handles the shapes produced below:
 *   "package.json (scripts)"      → "package.json"
 *   ".github/workflows/"          → ".github/workflows"
 *   "directory listing: `src/`"   → "src"
 *   "Dockerfile"                  → "Dockerfile"
 */
function pathFromSource(source: string | null): string | undefined {
  if (!source) return undefined
  const withExt = source.match(
    /^([^\s(`]+\.(?:json|ya?ml|toml|md|lock|lockb|txt|gradle|xml|csproj|sln|gemspec))(?=[\s(]|$)/i,
  )
  if (withExt) return withExt[1]
  if (source.endsWith("/")) return source.replace(/\/$/, "")
  const dir = source.match(/directory listing: `(.+?)\/`/)
  if (dir) return dir[1]
  if (/^(Dockerfile|Gemfile|Makefile|Cargo\.toml|go\.mod|go\.sum)$/i.test(source)) return source
  return undefined
}

/**
 * Build an evidence list by attributing each detected fact to the most likely
 * file that produced it. The mapping is deterministic from `RepoFacts` so we
 * don't need extra plumbing through the scanner.
 *
 * Pass `repoUrl` to attach clickable GitHub links to every sourced claim.
 */
export function buildEvidence(facts: RepoFacts, repoUrl?: string): EvidenceItem[] {
  const items: EvidenceItem[] = []

  // GitHub-level metadata — sourced from the repository itself
  items.push({
    field: "language",
    label: "Language",
    value: facts.language || null,
    source: facts.language ? "GitHub repository metadata" : null,
    verified: !!facts.language,
  })
  items.push({
    field: "description",
    label: "Description",
    value: facts.description || null,
    source: facts.description ? "GitHub repository metadata" : null,
    verified: !!facts.description,
  })
  items.push({
    field: "defaultBranch",
    label: "Default branch",
    value: facts.defaultBranch || null,
    source: "GitHub repository metadata",
    verified: !!facts.defaultBranch,
  })

  // package.json — JS / TS ecosystem
  const isJsTs =
    !!facts.packageManager &&
    ["npm", "pnpm", "yarn", "bun"].includes(facts.packageManager)
  const pkgSource = isJsTs ? "package.json" : null

  if (pkgSource) {
    items.push({
      field: "framework",
      label: "Framework",
      value: facts.framework,
      source: facts.framework ? "package.json (dependencies)" : null,
      sourceDetail: facts.framework ? `dependencies.${facts.framework.toLowerCase().replace(/[^a-z]/g, "")}` : undefined,
      verified: !!facts.framework,
    })
    items.push({
      field: "buildTool",
      label: "Build tool",
      value: facts.buildTool,
      source: facts.buildTool ? "package.json (dependencies)" : null,
      verified: !!facts.buildTool,
    })
    items.push({
      field: "testFramework",
      label: "Test framework",
      value: facts.testFramework,
      source: facts.testFramework ? "package.json (devDependencies)" : null,
      verified: !!facts.testFramework,
    })
    items.push({
      field: "devCommand",
      label: "Dev command",
      value: facts.devCommand,
      source: facts.devCommand ? "package.json (scripts)" : null,
      sourceDetail: "scripts.dev / scripts.start",
      verified: !!facts.devCommand,
    })
    items.push({
      field: "buildCommand",
      label: "Build command",
      value: facts.buildCommand,
      source: facts.buildCommand ? "package.json (scripts)" : null,
      sourceDetail: "scripts.build",
      verified: !!facts.buildCommand,
    })
    items.push({
      field: "testCommand",
      label: "Test command",
      value: facts.testCommand,
      source: facts.testCommand ? "package.json (scripts)" : null,
      sourceDetail: "scripts.test",
      verified: !!facts.testCommand,
    })
    items.push({
      field: "lintCommand",
      label: "Lint command",
      value: facts.lintCommand,
      source: facts.lintCommand ? "package.json (scripts)" : null,
      sourceDetail: "scripts.lint",
      verified: !!facts.lintCommand,
    })
  }

  // packageManager is verified by lockfile presence
  items.push({
    field: "packageManager",
    label: "Package manager",
    value: facts.packageManager,
    source: facts.packageManager ? lockfileFor(facts.packageManager) : null,
    verified: !!facts.packageManager,
  })

  // Directory-level facts — verified by file-tree presence
  items.push({
    field: "srcDir",
    label: "Source directory",
    value: facts.srcDir,
    source: facts.srcDir ? `directory listing: \`${facts.srcDir}/\`` : null,
    verified: !!facts.srcDir,
  })
  items.push({
    field: "testDir",
    label: "Test directory",
    value: facts.testDir,
    source: facts.testDir ? `directory listing: \`${facts.testDir}/\`` : null,
    verified: !!facts.testDir,
  })

  // Top-level config files
  items.push({
    field: "hasDocker",
    label: "Docker",
    value: facts.hasDocker ? "Present" : null,
    source: facts.hasDocker ? "Dockerfile" : null,
    verified: facts.hasDocker,
  })
  items.push({
    field: "hasCi",
    label: "CI/CD",
    value: facts.hasCi ? "Present" : null,
    source: facts.hasCi ? ".github/workflows/" : null,
    verified: facts.hasCi,
  })
  items.push({
    field: "hasReadme",
    label: "README",
    value: facts.hasReadme ? "Present" : null,
    source: facts.hasReadme ? "README.md" : null,
    verified: facts.hasReadme,
  })
  items.push({
    field: "hasAgentsMd",
    label: "AGENTS.md",
    value: facts.hasAgentsMd ? "Present" : null,
    source: facts.hasAgentsMd ? "AGENTS.md" : null,
    verified: facts.hasAgentsMd,
  })

  // Attach clickable GitHub URLs so the UI can jump straight to the source file
  if (repoUrl) {
    const base = repoUrl.replace(/\/$/, "")
    const branch = facts.defaultBranch || "HEAD"
    for (const it of items) {
      const p = pathFromSource(it.source)
      if (p) it.sourceUrl = `${base}/blob/${branch}/${p}`
    }
  }

  return items
}

function lockfileFor(pm: string | null): string | null {
  switch (pm) {
    case "pnpm":       return "pnpm-lock.yaml"
    case "yarn":       return "yarn.lock"
    case "bun":        return "bun.lockb"
    case "npm":        return "package-lock.json"
    case "poetry":     return "pyproject.toml (poetry.lock)"
    case "pip":        return "requirements.txt"
    case "go modules": return "go.mod"
    case "cargo":      return "Cargo.toml"
    default:          return null
  }
}
